name: Python Versions

on: push

jobs:
    ubuntu:
        name: ubuntu
        runs-on: ubuntu-latest
        steps:
            - run: date
    windows:
        name: windows
        runs-on: windows-latest
        steps:
            - run: date
    macos:
        name: macos
        runs-on: macos-latest
        steps:
            - run: date
    summary:
        name: summary
        runs-on: ubuntu-latest
        needs: [ubuntu, windows, macos]
        steps:
            - run: date
